cask_args appdir: "/Applications"
tap "homebrew/bundle"
brew "git"
brew "neovim"
brew "nodebrew"
brew "starship"
brew "tree"
brew "zsh-autosuggestions"
cask "google-chrome"
cask "docker"
cask "iterm2"
cask "zoom"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "visual-studio-code"
